In [2]:
import os
import sys

sys.path.append(os.path.dirname(os.getcwd())) 

import pandas as pd
import numpy as np

from datetime import datetime, timedelta

from src.constants import HEADERS

pd.set_option('display.max_columns', None)

In [23]:
from nba_api.stats.endpoints.boxscorefourfactorsv2 import BoxScoreFourFactorsV2
from nba_api.stats.endpoints.boxscoreplayertrackv2 import BoxScorePlayerTrackV2
from nba_api.stats.library.parameters import (
    EndPeriod,
    EndRange,
    RangeType,
    StartPeriod,
    StartRange,
)

In [24]:
pt = BoxScorePlayerTrackV2(
    game_id='0022200001'
)

In [27]:
pt.get_data_frames()[1]

,GAME_ID,TEAM_ID,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,DIST,ORBC,DRBC,RBC,TCHS,SAST,FTAST,PASS,AST,CFGM,CFGA,CFG_PCT,UFGM,UFGA,UFG_PCT,FG_PCT,DFGM,DFGA,DFG_PCT
0,0022200001,1610612755,76ers,PHI,Philadelphia,240:00,17.02,20,37,54,381,4,2,263,16,16,28,0.571,24,52,0.462,0.500,17,24,0.708
1,0022200001,1610612738,Celtics,BOS,Boston,240:00,16.61,18,51,67,376,3,2,263,24,19,32,0.594,27,50,0.540,0.561,12,18,0.667

In [45]:
g_id = ['0022200001','0022200002']
import time
df_g_list = []
for g in g_id: 
    time.sleep(1)
    ff = BoxScoreFourFactorsV2(
    game_id=g,
    # end_period=EndPeriod.default,
    # end_range=EndRange.default,
    # range_type=RangeType.default,
    # start_period=StartPeriod.default,
    # start_range=StartRange.default,
    )
    df_g_list.append(ff.get_data_frames()[1])
df_g = pd.concat(df_g_list)

In [46]:
df_g

,GAME_ID,TEAM_ID,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,EFG_PCT,FTA_RATE,TM_TOV_PCT,OREB_PCT,OPP_EFG_PCT,OPP_FTA_RATE,OPP_TOV_PCT,OPP_OREB_PCT
0,0022200001,1610612755,76ers,PHI,Philadelphia,240:00,0.581,0.350,0.143,0.190,0.634,0.341,0.113,0.256
1,0022200001,1610612738,Celtics,BOS,Boston,240:00,0.634,0.341,0.113,0.256,0.581,0.350,0.143,0.190
0,0022200002,1610612747,Lakers,LAL,Los Angeles,240:00,0.479,0.266,0.196,0.246,0.535,0.232,0.157,0.281
1,0022200002,1610612744,Warriors,GSW,Golden State,240:00,0.535,0.232,0.157,0.281,0.479,0.266,0.196,0.246

In [36]:
ff

In [39]:
ff.get_data_frames()

[       GAME_ID     TEAM_ID TEAM_ABBREVIATION     TEAM_CITY  PLAYER_ID  \
 0   0022200001  1610612755               PHI  Philadelphia     202699
 1   0022200001  1610612755               PHI  Philadelphia     200782
 2   0022200001  1610612755               PHI  Philadelphia     203954
 3   0022200001  1610612755               PHI  Philadelphia    1630178
 4   0022200001  1610612755               PHI  Philadelphia     201935
 5   0022200001  1610612755               PHI  Philadelphia    1626149
 6   0022200001  1610612755               PHI  Philadelphia    1629001
 7   0022200001  1610612755               PHI  Philadelphia    1627863
 8   0022200001  1610612755               PHI  Philadelphia    1627777
 9   0022200001  1610612755               PHI  Philadelphia    1629680
 10  0022200001  1610612755               PHI  Philadelphia    1627788
 11  0022200001  1610612755               PHI  Philadelphia    1629003
 12  0022200001  1610612755               PHI  Philadelphia    1630194
 13  0022200001  1610612755               PHI  Philadelphia    1630531
 14  0022200001  1610612738               BOS        Boston    1627759
 15  0022200001  1610612738               BOS        Boston    1628369
 16  0022200001  1610612738               BOS        Boston     201143
 17  0022200001  1610612738               BOS        Boston    1628401
 18  0022200001  1610612738               BOS        Boston     203935
 19  0022200001  1610612738               BOS        Boston     203943
 20  0022200001  1610612738               BOS        Boston    1629684
 21  0022200001  1610612738               BOS        Boston    1627763
 22  0022200001  1610612738               BOS        Boston     201933
 23  0022200001  1610612738               BOS        Boston    1630573
 24  0022200001  1610612738               BOS        Boston    1631120
 25  0022200001  1610612738               BOS        Boston    1628382
 26  0022200001  1610612738               BOS        Boston    1629662
 27  0022200001  1610612738               BOS        Boston    1628436
 28  0022200001  1610612738               BOS        Boston    1630202

           PLAYER_NAME    NICKNAME START_POSITION                 COMMENT  \
 0       Tobias Harris      Tobias              F
 1         P.J. Tucker        P.J.              F
 2         Joel Embiid        Joel              C
 3        Tyrese Maxey      Tyrese              G
 4        James Harden       James              G
 5    Montrezl Harrell    Montrezl
 6   De'Anthony Melton  De'Anthony
 7    Danuel House Jr.      Danuel
 8       Georges Niang     Georges
 9    Matisse Thybulle     Matisse
 10     Furkan Korkmaz      Furkan                 DNP - Coach's Decision
 11       Shake Milton       Shake                 DNP - Coach's Decision
 12          Paul Reed        Paul                 DNP - Coach's Decision
 13     Jaden Springer       Jaden                 DNP - Coach's Decision
 14       Jaylen Brown      Jaylen              F
 15       Jayson Tatum      Jayson              F
 16         Al Horford          Al              C
 17      Derrick White     Derrick              G
 18       Marcus Smart      Marcus              G
 19        Noah Vonleh        Noah
 20     Grant Williams       Grant
 21    Malcolm Brogdon     Malcolm
 22      Blake Griffin       Blake
 23         Sam Hauser         Sam
 24         JD Davison          JD                 DNP - Coach's Decision
 25     Justin Jackson      Justin                 DNP - Coach's Decision
 26  Mfiondu Kabengele     Mfiondu                 DNP - Coach's Decision
 27        Luke Kornet        Luke                 DNP - Coach's Decision
 28   Payton Pritchard      Payton                 DNP - Coach's Decision

       MIN  EFG_PCT  FTA_RATE  TM_TOV_PCT  OREB_PCT  OPP_EFG_PCT  OPP_FTA_RATE  \
 0   34:14    0.593     0.305       0.149     0.160        0.612         0.293
 1   33:01    0.580     0.304       0.156     0.167        0.636         0.309
 2   37:16    0.589     0.306       0.153     0.154        0.677         0.277
 3   38:12    0.590     0.269       0.134     0.148        0.636         0.303
 4   37:16    0.563     0.365       0.137     0.133        0.589         0.323
 5   10:44    0.556     0.500       0.083     0.000        0.471         0.588
 6   20:33    0.600     0.500       0.141     0.000        0.708         0.444
 7   16:12    0.560     0.440       0.118     0.000        0.643         0.393
 8   12:08    0.575     0.500       0.076     0.000        0.705         0.409
 9    0:24    0.000     0.000       0.000     0.000        0.000         2.000
 10   None      NaN       NaN         NaN       NaN          NaN           NaN
 11   None      NaN       NaN         NaN       NaN          NaN           NaN
 12   None      NaN       NaN         NaN       NaN          NaN           NaN
 13   None      NaN       NaN         NaN       NaN          NaN           NaN
 14  38:34    0.636     0.273       0.103     0.148        0.600         0.277
 15  38:37    0.643     0.349       0.116     0.154        0.539         0.344
 16  23:06    0.659     0.366       0.062     0.125        0.628         0.282
 17  24:02    0.581     0.512       0.075     0.158        0.512         0.405
 18  36:05    0.589     0.339       0.108     0.179        0.595         0.302
 19  20:10    0.700     0.257       0.050     0.091        0.672         0.250
 20  23:57    0.613     0.225       0.200     0.235        0.564         0.410
 21  23:52    0.667     0.310       0.123     0.333        0.556         0.500
 22   8:17    0.538     0.615       0.216     0.400        0.571         0.643
 23   3:19    1.000     0.600       0.137     0.000        0.667         0.333
 24   None      NaN       NaN         NaN       NaN          NaN           NaN
 25   None      NaN       NaN         NaN       NaN          NaN           NaN
 26   None      NaN       NaN         NaN       NaN          NaN           NaN
 27   None      NaN       NaN         NaN       NaN          NaN           NaN
 28   None      NaN       NaN         NaN       NaN          NaN           NaN

     OPP_TOV_PCT  OPP_OREB_PCT
 0         0.115         0.160
 1         0.076         0.087
 2         0.079         0.125
 3         0.076         0.077
 4         0.132         0.172
 5         0.214         0.333
 6         0.136         0.417
 7         0.172         0.400
 8         0.111         0.286
 9         0.000         0.000
 10          NaN           NaN
 11          NaN           NaN
 12          NaN           NaN
 13          NaN           NaN
 14        0.148         0.148
 15        0.136         0.133
 16        0.128         0.200
 17        0.147         0.143
 18        0.140         0.154
 19        0.169         0.077
 20        0.098         0.000
 21        0.157         0.067
 22        0.053         0.000
 23        0.127         0.000
 24          NaN           NaN
 25          NaN           NaN
 26          NaN           NaN
 27          NaN           NaN
 28          NaN           NaN  ,
       GAME_ID     TEAM_ID TEAM_NAME TEAM_ABBREVIATION     TEAM_CITY     MIN  \
 0  0022200001  1610612755     76ers               PHI  Philadelphia  240:00
 1  0022200001  1610612738   Celtics               BOS        Boston  240:00

    EFG_PCT  FTA_RATE  TM_TOV_PCT  OREB_PCT  OPP_EFG_PCT  OPP_FTA_RATE  \
 0    0.581     0.350       0.143     0.190        0.634         0.341
 1    0.634     0.341       0.113     0.256        0.581         0.350

    OPP_TOV_PCT  OPP_OREB_PCT
 0        0.113         0.256
 1        0.143         0.190  ]

In [13]:
ff.get_data_frames()[1]

,GAME_ID,TEAM_ID,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,EFG_PCT,FTA_RATE,TM_TOV_PCT,OREB_PCT,OPP_EFG_PCT,OPP_FTA_RATE,OPP_TOV_PCT,OPP_OREB_PCT
0,0022200001,1610612755,76ers,PHI,Philadelphia,240:00,0.581,0.350,0.143,0.190,0.634,0.341,0.113,0.256
1,0022200001,1610612738,Celtics,BOS,Boston,240:00,0.634,0.341,0.113,0.256,0.581,0.350,0.143,0.190

In [17]:
# EFG_PCT = (FGM + 0.5 x 3PM) / FGA
(40 + .5*13)/80, (46+.5*12)/82

(0.58125, 0.6341463414634146)

In [20]:
# FTA_RATE = FTA / FGA
28/80, 28/82

(0.35, 0.34146341463414637)

In [21]:
# TM_TOV_PCT = TOV / POSS
# POSS Est = FGA + (0.44 x FTA) + TOV - OREB
PHI_POSS_est = 80 + .44*28 + 14 - 4
BOS_POSS_est = 82 + .44*28 + 10 - 6
14/PHI_POSS_est, 10/BOS_POSS_est

(0.13682564503518374, 0.10170870626525631)

In [22]:
# OREB_PCT = OREB / (OREB + Opp DREB)
4/(4+30), 6/(6+27) # more off perhaps NBA uses a slightly different calculation

(0.11764705882352941, 0.18181818181818182)

In [29]:
4/20, 6/18

(0.2, 0.3333333333333333)

In [ ]:
def fetch_game_logs(self) -> pd.DataFrame:
        
        df_logs = pd.DataFrame()

        for season in self.season_list:
            logger.info(f"Fetching game logs for season {season}")
            lgl = LeagueGameLog(
                counter=0,
                direction=Direction.default,
                league_id=LeagueID.default,
                player_or_team_abbreviation=PlayerOrTeamAbbreviation.default,
                season=season,
                season_type_all_star=SeasonTypeAllStar.default,
                sorter=Sorter.default,
                date_from_nullable="",
                date_to_nullable="",
                proxy=None,
                headers=None,
                timeout=30,
                get_request=True
            )
            df_lgl = lgl.get_data_frames()[0]
            df_logs = pd.concat([df_logs, df_lgl])
            logger.info(f"--> Appended {len(df_lgl)/2} games from season {season}")
            self.game_ids = df_logs['GAME_ID'].unique()

        self.summarize_game_logs(df_logs)

        return df_logs